spring.application.name=mini-library
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_library
spring.datasource.username=postgres
spring.datasource.password=Arup2708@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=kdoivcvnreuh7v3j1j2u3h488n98yrw9vjsnfus9jonfdg5dfgwrtefg2+dfg8d4g
